<a href="https://colab.research.google.com/github/AYUshJaiswal454/Harsh-Sir-Classes/blob/main/Lecture_6(Pandas).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

dct = {
    'name': ['Tom','Dick','Harry'],
    'age': [20,27,19],
    'roll':[1,2,3]
}

df = pd.DataFrame(dct)
df1 = pd.DataFrame(dct,index = ['a','b','c'])
display(df)
display(df1)
# print(df)

    name  age  roll
0    Tom   20     1
1   Dick   27     2
2  Harry   19     3

    name  age  roll
a    Tom   20     1
b   Dick   27     2
c  Harry   19     3

In [4]:
df = pd.read_csv('student_data.csv')
# display(df)
display(df.head())

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed

In [5]:
import pandas as pd

file_ = pd.read_csv('student_data.csv', sep=',')
# print(file_)
print(file_.head())

   study_hours  attendance  sleep_hours  internet_usage  \
0            7          56            8               7
1            4          69            5               3
2           11          60            7               6
3            8          99            9               8
4            5          52            8               6

   assignments_completed  previous_score  exam_score placement_status
0                     10              62      100.00           Placed
1                      8              56      100.00           Placed
2                     10              45      100.00           Placed
3                      4              55       90.17           Placed
4                      8              40       78.82           Placed

In [ ]:
df = pd.read_csv('student_data.csv')
display(df)


# df.shape(500,8)


#

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [ ]:
df = pd.read_csv('student_data.csv')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   study_hours            10000 non-null  int64
 1   attendance             10000 non-null  int64
 2   sleep_hours            10000 non-null  int64
 3   internet_usage         10000 non-null  int64
 4   assignments_completed  10000 non-null  int64
 5   previous_score         10000 non-null  int64
 6   exam_score             10000 non-null  float64
 7   placement_status       10000 non-null  object
dtypes: float64(1), int64(6), object(1)
memory usage: 625.1+ KB

In [ ]:
df = pd.read_csv('student_data.csv')
df.tail()

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [ ]:
df = pd.read_csv('student_data.csv')
df.describe()

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score
count,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000
mean,5.989600,69.88460,6.498500,6.062600,9.988400,64.91100,86.704207
std,3.163589,17.61653,1.709354,3.138163,6.034145,17.50302,15.058383
min,1.000000,40.00000,4.000000,1.000000,0.000000,35.00000,26.670000
25%,3.000000,55.00000,5.000000,3.000000,5.000000,50.00000,76.727500
50%,6.000000,70.00000,6.500000,6.000000,10.000000,65.00000,92.120000
75%,9.000000,85.00000,8.000000,9.000000,15.000000,80.00000,100.000000
max,11.000000,100.00000,9.000000,11.000000,20.000000,95.00000,100.000000

q2(2nd quartile)->Median




q1(1st quartile)->Median from first to median




q3(3rd quartile)->Median from median to last

In [ ]:
df = pd.read_csv('student_data.csv')
df.tail(4)

df[['study_hours','internet_usage']]

      study_hours  internet_usage
0               7               7
1               4               3
2              11               6
3               8               8
4               5               6
...           ...             ...
9995            2               7
9996            7               9
9997           10               5
9998           10               5
9999            2              11

[10000 rows x 2 columns]

In [ ]:
df = pd.read_csv('student_data.csv')
df.iloc[0:5]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed

In [ ]:
df = pd.read_csv('student_data.csv')

df.loc[df['study_hours'] == 11, ['study_hours','sleep_hours']].iloc[4:8]

     study_hours  sleep_hours
30            11            5
91            11            9
98            11            6
116           11            7

In [ ]:
# Question-> to access 2nd 8 in assignment completed

df = pd.read_csv('student_data.csv')
df.loc[df['assignments_completed'] == 8].iloc[1]

study_hours                   5
attendance                   52
sleep_hours                   8
internet_usage                6
assignments_completed         8
previous_score               40
exam_score                78.82
placement_status         Placed
Name: 4, dtype: object

In [ ]:
df = pd.read_csv('student_data.csv')
df[df["assignments_completed"] > 3]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [ ]:
df = pd.read_csv('student_data.csv')
# df["age"] = 20
df[df["assignments_completed"] > 3]

df

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [ ]:
df = pd.read_csv('student_data.csv')
df = df.rename(columns = {'assignments_completed':'assign_completed'})
df

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [ ]:
df = pd.read_csv('student_data.csv')
df.rename(columns = {'assignments_completed': 'assign_completed'},inplace = True)
display(df)

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [ ]:
df = pd.read_csv('student_data.csv')
# Correcting the syntax error and filtering rows where 'assignments_completed' is not equal to 8
df = df[df['assignments_completed'] != 8]
# If the intention was to drop a column named 'assignments_completed', use:
# df = df.drop(columns='assignments_completed')

SyntaxError: positional argument follows keyword argument (1423066642.py, line 2)

In [ ]:
df = pd.read_csv('student_data.csv')
df.sort_values(1, inplace=True)

KeyError: 1